language: bash

services:
 - docker

before_install:
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 - cd docker
 - docker build -t gkiar/fuzzy:ubuntu14.04-base -f Dockerfile.ubuntu14.04-verificarlo .
 - docker build -t gkiar/fuzzy:ubuntu14.04-blas-lapack -f Dockerfile.ubuntu14.04-blas-lapack .

script:
 - docker images