language: bash

services:
  -docker

install:
 - cd docker
 - docker build -t gkiar/fuzzy:ubuntu14.04-base -f Dockerfile.ubuntu14.04-verificarlo .
 - docker build -t gkiar/fuzzy:ubuntu14.04-blas-lapack -f Dockerfile.ubuntu14.04-blas-lapack .

script:
 - docker images