language: bash

services:
 - docker

git:
 submodules: false

jobs:
 include:
  - stage: Base
    name: Verificarlo
    env: DFILE=base/Dockerfile.verificarlo  DIMAGE=base
  - stage: Environments (Level 1)
    name: Blas & Lapack
    env: DFILE=level1/Dockerfile.blas-lapack  DIMAGE=blas-lapack
  - name: Python
    env: DFILE=level1/Dockerfile.python       DIMAGE=python
  - name: Libmath
    env: DFILE=level1/Dockerfile.libmath DIMAGE=libmath
  - stage: Environments (Level 2)
    name: Python & Numpy
    env: DFILE=level2/Dockerfile.python-numpy DIMAGE=python-numpy
  - stage: Applications
    name: FSL
    env: DFILE=apps/fsl/Dockerfile.libmath-fsl DIMAGE=libmath-fsl
  - name: AFNI
    env: DFILE=apps/afni/Dockerfile.libmath-afni DIMAGE=libmath-afni
  - name: AFQ (Dipy)
    env: DFILE=apps/dipy-afq/Dockerfile.python-numpy-dipy-afq DIMAGE=python-numpy-dipy-afq
  - name: AFQ (Dipy) -- Python Only
    env: DFILE=apps/dipy-afq/Dockerfile.python-dipy-afq DIMAGE=python-dipy-afq
  - name: PyTorch
    env: DFILE=apps/pytorch/Dockerfile.pytorch DIMAGE=pytorch

script:
 - ./fuzzy/build/login.sh
 - ./fuzzy/build/build.sh ${DFILE} ${DIMAGE}
 # - travis_wait 30 ./fuzzy/build/build.sh ${DFILE} ${DIMAGE}

# Publish early stages always, only publish applications when we have a new tag (temporary)
# - if [ "$TRAVIS_TAG" != "" ] || [ "$TRAVIS_BUILD_STAGE_NAME" != "App" ]; then ./fuzzy/build/push.sh ${DIMAGE}; fi

# Publish always after success
after_script:
  - ./fuzzy/build/push.sh ${DIMAGE}
