language: bash

services:
 - docker

jobs:
 include:
  - stage: Base
    name: Verificarlo
    env: DFILE=Dockerfile.ubuntu14.04-verificarlo  DIMAGE=ubuntu14.04-base
  - stage: Environments (Level 1)
    name: Blas & Lapack
    env: DFILE=Dockerfile.ubuntu14.04-blas-lapack  DIMAGE=ubuntu14.04-blas-lapack
  - name: Python
    env: DFILE=Dockerfile.ubuntu14.04-python       DIMAGE=ubuntu14.04-python
  - stage: Environments (Level 2)
    name: "reapeat (tmp)"
    env: DFILE=Dockerfile.ubuntu14.04-python       DIMAGE=ubuntu14.04-python

script:
 - ./login.sh 
 - ./build.sh ${DFILE} ${DIMAGE}
 
after_script:
 - if [ "$TRAVIS_TAG" != "" ]; then ./push.sh ${DIMAGE}; fi
