name: docker build with cache

on:
  pull_request:
    branches: [ master, 'releases/**' ]
  push:
    branches: [ master, 'releases/**' ]

jobs:
  lapack:
    runs-on: ubuntu-20.04
    steps:
      # Check out code
      - name: Checkout
        uses: actions/checkout@v2
      # This is the a separate action that sets up buildx runner
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Pull previous build
        run: docker pull verificarlo/fuzzy:v0.4.1-lapack
        continue-on-error: true
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./fuzzy/docker/base/Dockerfile.ubuntu20.04-lapack
          push: true
          tags: verificarlo/fuzzy:v0.4.1-lapack
          cache-from: verificarlo/fuzzy:v0.4.1-lapack
