name: Docker build Python and push

on:
  pull_request:
    branches: [ master, 'releases/**' ]
  push:
    branches: [ master, 'releases/**' ]

jobs:
  lapack:
    runs-on: ubuntu-20.04
    env:
      DOCKER_IMAGE: verificarlo/fuzzy:v0.4.1-lapack
      DOCKER_FILE: ./fuzzy/docker/base/Dockerfile.ubuntu20.04-lapack
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Checkout repository
        uses: actions/checkout@v2
      -
        name: Verify that Dockerfiles have changed
        uses: tj-actions/verify-changed-files@v5.5
        id: changed_files
        with:
          files: ./fuzzy/docker/
      -
        name: Cancel upstream jobs
        if: contains(steps.changed_files.outputs.changed_files, './fuzzy/docker')
        uses: n1hility/cancel-previous-runs@v2
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ${DOCKER_FILE} 
          push: true
          tags: ${DOCKER_IMAGE}
          cache-from: ${DOCKER_IMAGE}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  python:
    needs: lapack
    runs-on: ubuntu-20.04
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Checkout repository
        uses: actions/checkout@v2
      -
        name: Pull previous build
        run: docker pull verificarlo/fuzzy:v0.4.1-lapack-python3.8.5
        continue-on-error: true
      -
        name: Build fuzzy python docker and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./fuzzy/docker/level1/Dockerfile.ubuntu20.04-python
          push: true
          tags: verificarlo/fuzzy:v0.4.1-lapack-python3.8.5
          cache-from: verificarlo/fuzzy:v0.4.1-lapack-python3.8.5
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

#  python_numpy:
#    needs: python
#    runs-on: ubuntu-20.04
#    steps:
#      -
#        name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#      -
#        name: Login to DockerHub
#        uses: docker/login-action@v1 
#        with:
#          username: ${{ secrets.DOCKER_HUB_USERNAME }}
#          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#      -
#        name: Check Out Repo 
#        uses: actions/checkout@v2
#      -
#        name: Build fuzzy Numpy docker and push
#        id: docker_build
#        uses: docker/build-push-action@v2
#        with:
#          context: ./
#          file: ./fuzzy/docker/level2/Dockerfile.ubuntu20.04-python-numpy
#          push: true
#          tags: yohanchatelain/fuzzy:python-numpy-v0.4.1
#      -
#        name: Image digest
#        run: echo ${{ steps.docker_build.outputs.digest }}
#
#  python_numpy_scipy:
#      needs: python_numpy
#      runs-on: ubuntu-20.04
#      steps:
#        -
#          name: Set up Docker Buildx
#          uses: docker/setup-buildx-action@v1
#        -
#          name: Login to DockerHub
#          uses: docker/login-action@v1 
#          with:
#            username: ${{ secrets.DOCKER_HUB_USERNAME }}
#            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#        -
#          name: Check Out Repo 
#          uses: actions/checkout@v2
#        -
#          name: Build fuzzy Scipy docker and push
#          id: docker_build
#          uses: docker/build-push-action@v2
#          with:
#            context: ./
#            file: ./fuzzy/docker/level3/Dockerfile.ubuntu20.04-python-numpy-scipy
#            push: true
#            tags: yohanchatelain/fuzzy:python-numpy-scipy-v0.4.1
#        -
#          name: Image digest
#          run: echo ${{ steps.docker_build.outputs.digest }}
#
#  python_numpy_scipy_sklearn:
#      needs: python_numpy_scipy
#      runs-on: ubuntu-20.04
#      steps:
#        -
#          name: Set up Docker Buildx
#          uses: docker/setup-buildx-action@v1
#        -
#          name: Login to DockerHub
#          uses: docker/login-action@v1 
#          with:
#            username: ${{ secrets.DOCKER_HUB_USERNAME }}
#            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#        -
#          name: Check Out Repo 
#          uses: actions/checkout@v2
#        -
#          name: Build fuzzy Scikit-learn docker and push
#          id: docker_build
#          uses: docker/build-push-action@v2
#          with:
#            context: ./
#            file: ./fuzzy/docker/level4/Dockerfile.ubuntu20.04-python-numpy-scipy-sklearn
#            push: true
#            tags: yohanchatelain/fuzzy:python-numpy-scipy-sklearn-v0.4.1
#        -
#          name: Image digest
#          run: echo ${{ steps.docker_build.outputs.digest }}
