name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image fuzzy
      run: docker build . --file fuzzy/docker/level1/Dockerfile.ubuntu20.08-python --tag fuzzy
    - name: Build the Docker image fuzzy-numpy
      run: docker build . --file fuzzy/docker/level2/Dockerfile.ubuntu20.08-python-numpy --tag fuzzy-numpy
    - name: Build the Docker image fuzzy-numpy-scipy
      run: docker build . --file fuzzy/docker/level3/Dockerfile.ubuntu20.08-python-numpy-scipy --tag fuzzy-numpy-scipy
    - name: Build the Docker image fuzzy-numpy-scipy-sklearn
      run: docker build . --file fuzzy/docker/level4/Dockerfile.ubuntu20.08-python-numpy-scipy-sklearn --tag fuzzy-numpy-scipy-sklearn
